# 简化版 Docker Compose 配置 - 只包含 Astro 应用
# 现代 Docker Compose 格式（不需要 version 字段）

services:
  astro-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: astro-react-app
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    volumes:
      # 持久化用户数据
      - ./data:/app/data
    restart: unless-stopped
    # 资源限制（使用新格式）
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25' 